use_frameworks!

target 'HTUIExtensions_Example' do
  pod 'HTUIExtensions', :path => '../'

  target 'HTUIExtensions_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
